# This file was generated by GoReleaser. DO NOT EDIT.
class Giturl < Formula
  desc "A converter for Git URLs."
  homepage "https://github.com/nakabonne/giturl"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nakabonne/giturl/releases/download/v0.1.1/giturl_0.1.1_Darwin_x86_64.tar.gz"
    sha256 "cf1af911ff13e0325dd69f997cf99993a90dbefeaaa6965c3270deb4de71b249"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nakabonne/giturl/releases/download/v0.1.1/giturl_0.1.1_Linux_x86_64.tar.gz"
      sha256 "8350352d6394e431880bf403a46074f023e80526f2bc01a372a61cba4afd1b97"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nakabonne/giturl/releases/download/v0.1.1/giturl_0.1.1_Linux_arm64.tar.gz"
        sha256 "62184a5bad7ad74acbccb9eb741ce08917e3371788bbb7f0432e957df68626de"
      else
        url "https://github.com/nakabonne/giturl/releases/download/v0.1.1/giturl_0.1.1_Linux_armv6.tar.gz"
        sha256 "0632921a348404130b734e24940231ab12035f5c263b80e652362b88026b0943"
      end
    end
  end

  def install
    bin.install "giturl"
  end
end
